/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zaptox.zaptoxpos.frames;

import java.awt.Color;
import java.awt.GridBagLayout;
import javax.swing.JFrame;

/**
 *
 * @author Dell
 */
public class DashBoardPage extends javax.swing.JFrame {

    /**
     * Creates new form DashBoardPage
     */
    ProductInternalFrame product_frame;
    UserInternalFrame user_frame;

    public DashBoardPage() {
        initComponents();
        product_frame = new ProductInternalFrame();
        user_frame = new UserInternalFrame();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMin = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabelHeaderRow = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonViewUser = new javax.swing.JButton();
        jButtonViewProducts = new javax.swing.JButton();
        jButtonViewUser5 = new javax.swing.JButton();
        jButtonView3 = new javax.swing.JButton();
        jButtonViewUser9 = new javax.swing.JButton();
        jButtonViewUser6 = new javax.swing.JButton();
        jButtonViewUser10 = new javax.swing.JButton();
        jButtonViewUser11 = new javax.swing.JButton();
        jButtonViewUser12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMin.setBackground(new java.awt.Color(255, 0, 0));
        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin.setText("-");
        jLabelMin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 50, 40));

        jLabelExit.setBackground(new java.awt.Color(0, 102, 255));
        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("X");
        jLabelExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelExit.setOpaque(true);
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
        });
        getContentPane().add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 50, 40));

        jLabelHeaderRow.setBackground(new java.awt.Color(0, 102, 255));
        jLabelHeaderRow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHeaderRow.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHeaderRow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeaderRow.setText("DashBoard");
        jLabelHeaderRow.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelHeaderRow.setOpaque(true);
        getContentPane().add(jLabelHeaderRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1110, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 1130, 680));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 240, 60));

        jButtonViewUser.setBackground(new java.awt.Color(255, 255, 255));
        jButtonViewUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonViewUser.setForeground(new java.awt.Color(0, 102, 255));
        jButtonViewUser.setText("User");
        jButtonViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewUserActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonViewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 50));

        jButtonViewProducts.setBackground(new java.awt.Color(255, 255, 255));
        jButtonViewProducts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonViewProducts.setForeground(new java.awt.Color(0, 102, 255));
        jButtonViewProducts.setText("Products");
        jButtonViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewProductsActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonViewProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 220, 50));

        jButtonViewUser5.setBackground(new java.awt.Color(255, 255, 255));
        jButtonViewUser5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonViewUser5.setForeground(new java.awt.Color(0, 102, 255));
        jButtonViewUser5.setText("View User");
        jButtonViewUser5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewUser5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonViewUser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 50));

        jButtonView3.setBackground(new java.awt.Color(255, 255, 255));
        jButtonView3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonView3.setForeground(new java.awt.Color(0, 102, 255));
        jButtonView3.setText("View User");
        jButtonView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonView3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonView3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 50));

        jButtonViewUser9.setBackground(new java.awt.Color(255, 255, 255));
        jButtonViewUser9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonViewUser9.setForeground(new java.awt.Color(0, 102, 255));
        jButtonViewUser9.setText("View User");
        jButtonViewUser9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewUser9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonViewUser9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 50));

        jButtonViewUser6.setBackground(new java.awt.Color(255, 255, 255));
        jButtonViewUser6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonViewUser6.setForeground(new java.awt.Color(0, 102, 255));
        jButtonViewUser6.setText("View User");
        jButtonViewUser6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewUser6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonViewUser6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, 50));

        jButtonViewUser10.setBackground(new java.awt.Color(255, 255, 255));
        jButtonViewUser10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonViewUser10.setForeground(new java.awt.Color(0, 102, 255));
        jButtonViewUser10.setText("View User");
        jButtonViewUser10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewUser10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonViewUser10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 220, 50));

        jButtonViewUser11.setBackground(new java.awt.Color(255, 255, 255));
        jButtonViewUser11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonViewUser11.setForeground(new java.awt.Color(0, 102, 255));
        jButtonViewUser11.setText("View User");
        jButtonViewUser11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewUser11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonViewUser11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 220, 50));

        jButtonViewUser12.setBackground(new java.awt.Color(255, 255, 255));
        jButtonViewUser12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonViewUser12.setForeground(new java.awt.Color(0, 102, 255));
        jButtonViewUser12.setText("View User");
        jButtonViewUser12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewUser12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonViewUser12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 220, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 580));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zaptox/zaptoxpos/images/logo.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        // TODO add your handling code here:

        this.jLabelExit.setBackground(Color.red);
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        // TODO add your handling code here:
        this.jLabelExit.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_jLabelExitMouseExited

    private void jButtonViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewUserActionPerformed
        // TODO add your handling code here:
        try {
            this.jDesktopPane1.add(user_frame);
            user_frame.show();
            if (product_frame.isVisible()) {
                product_frame.hide();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonViewUserActionPerformed

    private void jButtonViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewProductsActionPerformed
        // TODO add your handling code here:
//
        try {
            this.jDesktopPane1.add(product_frame);
            product_frame.show();
            if (user_frame.isVisible()) {
                user_frame.hide();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonViewProductsActionPerformed

    private void jButtonViewUser5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewUser5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewUser5ActionPerformed

    private void jButtonView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonView3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonView3ActionPerformed

    private void jButtonViewUser9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewUser9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewUser9ActionPerformed

    private void jButtonViewUser6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewUser6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewUser6ActionPerformed

    private void jButtonViewUser10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewUser10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewUser10ActionPerformed

    private void jButtonViewUser11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewUser11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewUser11ActionPerformed

    private void jButtonViewUser12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewUser12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewUser12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonView3;
    private javax.swing.JButton jButtonViewProducts;
    private javax.swing.JButton jButtonViewUser;
    private javax.swing.JButton jButtonViewUser10;
    private javax.swing.JButton jButtonViewUser11;
    private javax.swing.JButton jButtonViewUser12;
    private javax.swing.JButton jButtonViewUser5;
    private javax.swing.JButton jButtonViewUser6;
    private javax.swing.JButton jButtonViewUser9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelHeaderRow;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
