/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zaptox.zaptoxpos.dialog;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import zaptox.zaptoxpos.beans.User;
import zaptox.zaptoxpos.beans.UserType;
import zaptox.zaptoxpos.dao.DbManager;
import zaptox.zaptoxpos.dao.DbManagerInterface;
import zaptox.zaptoxpos.util.playAudio;

/**
 *
 * @author Vksoni
 */
public class DialogBox extends javax.swing.JDialog {

    /**
     * Creates new form DialogBox
     */
    DefaultComboBoxModel comboBoxModelUserType;
    public ArrayList<UserType> user_types_list;
    public ArrayList<User> users_list;
    DbManagerInterface dbManager;

    public DialogBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dbManager = new DbManager();
        user_types_list = dbManager.getAllUsersType();
        comboBoxModelUserType = (DefaultComboBoxModel) this.jComboBoxUserType.getModel();
        this.jComboBoxUserType.setVisible(true);
        showInUserTypesComboBox();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jComboBoxUserType = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jTextFieldContact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxUserType2 = new javax.swing.JComboBox<>();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTextFieldPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFieldRetypePassword = new javax.swing.JPasswordField();
        jLabelRetype = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextFieldName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonSave1 = new javax.swing.JButton();
        jButtonSave2 = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabelExit = new javax.swing.JLabel();
        jLabelHeaderRow = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("USER TYPE*");

        jComboBoxUserType.setBackground(new java.awt.Color(0, 102, 255));
        jComboBoxUserType.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUserTypeActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 270, -1));

        jTextFieldContact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldContact.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldContact.setText("Enter Contact...");
        jTextFieldContact.setBorder(null);
        jTextFieldContact.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldContactMouseClicked(evt);
            }
        });
        jTextFieldContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactActionPerformed(evt);
            }
        });
        jTextFieldContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldContactKeyPressed(evt);
            }
        });
        jPanel7.add(jTextFieldContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 270, 20));

        jLabel10.setBackground(new java.awt.Color(0, 0, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("CONTACT*");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 150, 20));
        jPanel7.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 270, -1));

        jTextFieldAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAddress.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldAddress.setText("Enter Address..");
        jTextFieldAddress.setBorder(null);
        jTextFieldAddress.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldAddressMouseClicked(evt);
            }
        });
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });
        jTextFieldAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAddressKeyPressed(evt);
            }
        });
        jPanel7.add(jTextFieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 270, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 51));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("ADDRESS*");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("USER TYPE*");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 400, -1));

        jComboBoxUserType2.setBackground(new java.awt.Color(0, 102, 255));
        jComboBoxUserType2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxUserType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUserType2ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBoxUserType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 560, -1));
        jPanel7.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 560, -1));
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 260, -1));

        jTextFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUsername.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsername.setText("Enter Username...");
        jTextFieldUsername.setBorder(null);
        jTextFieldUsername.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUsernameMouseClicked(evt);
            }
        });
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        jTextFieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsernameKeyPressed(evt);
            }
        });
        jPanel7.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 20));

        jLabel6.setBackground(new java.awt.Color(0, 0, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("USERNAME*");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, -1));
        jPanel7.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, -1));

        jTextFieldPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPassword.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldPassword.setText("Enter Password...");
        jTextFieldPassword.setBorder(null);
        jTextFieldPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPasswordMouseClicked(evt);
            }
        });
        jTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordActionPerformed(evt);
            }
        });
        jTextFieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPasswordKeyPressed(evt);
            }
        });
        jPanel7.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 260, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("PASSWORD*");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 260, -1));

        jTextFieldRetypePassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldRetypePassword.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldRetypePassword.setText("Retype Password...");
        jTextFieldRetypePassword.setBorder(null);
        jTextFieldRetypePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRetypePasswordMouseClicked(evt);
            }
        });
        jTextFieldRetypePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRetypePasswordActionPerformed(evt);
            }
        });
        jTextFieldRetypePassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRetypePasswordKeyPressed(evt);
            }
        });
        jPanel7.add(jTextFieldRetypePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 260, -1));

        jLabelRetype.setBackground(new java.awt.Color(0, 0, 51));
        jLabelRetype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRetype.setText("RETYPE PASSWORD*");
        jPanel7.add(jLabelRetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, -1));
        jPanel7.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 270, -1));

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldName.setText("Enter Name..");
        jTextFieldName.setBorder(null);
        jTextFieldName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNameMouseClicked(evt);
            }
        });
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyPressed(evt);
            }
        });
        jPanel7.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 270, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("NAME*");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 60, -1));

        jButtonSave.setBackground(new java.awt.Color(0, 102, 255));
        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave.setText("Save");
        jButtonSave.setBorder(null);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 290, 70));

        jButtonSave1.setBackground(new java.awt.Color(0, 102, 255));
        jButtonSave1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave1.setText("Save");
        jButtonSave1.setBorder(null);
        jButtonSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSave1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 290, 70));

        jButtonSave2.setBackground(new java.awt.Color(0, 102, 255));
        jButtonSave2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave2.setText("Save");
        jButtonSave2.setBorder(null);
        jButtonSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSave2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonSave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 170, 30));

        jButtonClear.setBackground(new java.awt.Color(0, 102, 255));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("Clear");
        jButtonClear.setBorder(null);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 180, 30));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 610, 310));

        jLabelExit.setBackground(new java.awt.Color(0, 102, 255));
        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("X");
        jLabelExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelExit.setOpaque(true);
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
        });
        getContentPane().add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 50, 40));

        jLabelHeaderRow.setBackground(new java.awt.Color(0, 102, 255));
        jLabelHeaderRow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHeaderRow.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHeaderRow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeaderRow.setText("User");
        jLabelHeaderRow.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelHeaderRow.setOpaque(true);
        getContentPane().add(jLabelHeaderRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        // TODO add your handling code here:

        this.jLabelExit.setBackground(Color.red);
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        // TODO add your handling code here:
        this.jLabelExit.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_jLabelExitMouseExited

    private void jComboBoxUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUserTypeActionPerformed

    private void jTextFieldAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAddressKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldAddress.getText().equalsIgnoreCase("Enter Address..")) {
            this.jTextFieldAddress.setText("");
            this.jTextFieldAddress.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldAddressKeyPressed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jTextFieldAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldAddressMouseClicked
        // TODO add your handling code here:

        if (this.jTextFieldAddress.getText().equalsIgnoreCase("Enter Address..")) {
            this.jTextFieldAddress.setText("");
            this.jTextFieldAddress.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldAddressMouseClicked

    private void jTextFieldContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldContactKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldContact.getText().equalsIgnoreCase("Enter Contact...")) {
            this.jTextFieldContact.setText("");
            this.jTextFieldContact.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldContactKeyPressed

    private void jTextFieldContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactActionPerformed

    private void jTextFieldContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldContactMouseClicked
        // TODO add your handling code here:

        if (this.jTextFieldContact.getText().equalsIgnoreCase("Enter Contact...")) {
            this.jTextFieldContact.setText("");
            this.jTextFieldContact.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldContactMouseClicked

    private void jComboBoxUserType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUserType2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUserType2ActionPerformed

    private void jTextFieldUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUsernameMouseClicked
        // TODO add your handling code here:

        if (this.jTextFieldUsername.getText().equalsIgnoreCase("Enter Username...")) {
            this.jTextFieldUsername.setText("");
            this.jTextFieldUsername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldUsernameMouseClicked

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jTextFieldUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsernameKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldUsername.getText().equalsIgnoreCase("Enter Username...")) {
            this.jTextFieldUsername.setText("");
            this.jTextFieldUsername.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldUsernameKeyPressed

    private void jTextFieldPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPasswordMouseClicked
        if (this.jTextFieldPassword.getText().equalsIgnoreCase("Enter Password...")) {
            this.jTextFieldPassword.setText("");
            this.jTextFieldPassword.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldPasswordMouseClicked

    private void jTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordActionPerformed

    private void jTextFieldPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPasswordKeyPressed
        if (this.jTextFieldPassword.getText().equalsIgnoreCase("Enter Password...")) {
            this.jTextFieldPassword.setText("");
            this.jTextFieldPassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextFieldPasswordKeyPressed

    private void jTextFieldRetypePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRetypePasswordMouseClicked
        // TODO add your handling code here:
        if (this.jTextFieldRetypePassword.getText().equalsIgnoreCase("Retype Password...")) {
            this.jTextFieldRetypePassword.setText("");
            this.jTextFieldRetypePassword.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldRetypePasswordMouseClicked

    private void jTextFieldRetypePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRetypePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRetypePasswordActionPerformed

    private void jTextFieldRetypePasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRetypePasswordKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldRetypePassword.getText().equalsIgnoreCase("Retype Password...")) {
            this.jTextFieldRetypePassword.setText("");
            this.jTextFieldRetypePassword.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldRetypePasswordKeyPressed

    private void jTextFieldNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMouseClicked
        // TODO add your handling code here:
        if (this.jTextFieldName.getText().equalsIgnoreCase("Enter Name..")) {
            this.jTextFieldName.setText("");
            this.jTextFieldName.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldNameMouseClicked

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldName.getText().equalsIgnoreCase("Enter Name..")) {
            this.jTextFieldName.setText("");
            this.jTextFieldName.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldNameKeyPressed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        int user_type_id = user_types_list.get(this.jComboBoxUserType.getSelectedIndex()).getUser_type_id();

        String username = this.jTextFieldUsername.getText();
        String password = this.jTextFieldPassword.getText();
        String reTypePassword = this.jTextFieldRetypePassword.getText();
        String name = this.jTextFieldName.getText();
        String contact = this.jTextFieldContact.getText();
        String address = this.jTextFieldAddress.getText();

        if (!(username.equalsIgnoreCase("Enter Username...") || password.equalsIgnoreCase("Enter Password...")
                || reTypePassword.equalsIgnoreCase("Retype Password...")
                || name.equalsIgnoreCase("Enter Name..") || username.equalsIgnoreCase("") || password.equalsIgnoreCase("")
                || reTypePassword.equalsIgnoreCase("")
                || name.equalsIgnoreCase("") || name.equalsIgnoreCase("") || contact.equals("Enter Contact...") || contact.equals("") || address.equals("Enter Address..") || address.equals(""))) {

            if (reTypePassword.equals(password)) {
                if (contact.matches("^[0][1-9]\\d{9}$|^[1-9]\\d{9}$")) {
                    int status = dbManager.insertUser(
                            new User(0, user_type_id, this.jTextFieldUsername.getText(), this.jTextFieldPassword.getText(),
                                    this.jTextFieldName.getText(),
                                    address, contact, 1));

                    if (status != 0) {

                        this.jTextFieldUsername.setText("Enter Username...");
                        this.jTextFieldPassword.setText("Enter Password...");
                        this.jTextFieldRetypePassword.setText("Retype Password...");
                        this.jTextFieldContact.setText("Enter Contact..");
                        this.jTextFieldAddress.setText("Enter Address...");
                        this.jTextFieldName.setText("Enter Name..");
                        this.jComboBoxUserType.setSelectedIndex(0);

                        this.jLabelRetype.setForeground(Color.gray);
                        this.jTextFieldUsername.setForeground(Color.gray);
                        this.jTextFieldPassword.setForeground(Color.gray);
                        this.jTextFieldRetypePassword.setForeground(Color.gray);
                        this.jTextFieldContact.setForeground(Color.gray);
                        this.jTextFieldAddress.setForeground(Color.gray);
                        this.jTextFieldName.setForeground(Color.gray);

                    }
                } else {
                    new playAudio().playErrorSound();

                    JOptionPane.showMessageDialog(this, "Invalid phone number", "Error", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                new playAudio().playErrorSound();
                this.jLabelRetype.setForeground(Color.red);
                JOptionPane.showMessageDialog(this, "Password not match", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            new playAudio().playErrorSound();

            JOptionPane.showMessageDialog(this, "Please fill required field", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSave1ActionPerformed

        int user_type_id = user_types_list.get(this.jComboBoxUserType.getSelectedIndex()).getUser_type_id();

        String username = this.jTextFieldUsername.getText();
        String password = this.jTextFieldPassword.getText();
        String reTypePassword = this.jTextFieldRetypePassword.getText();
        String name = this.jTextFieldName.getText();
        String contact = this.jTextFieldContact.getText();
        String address = this.jTextFieldAddress.getText();

        if (!(username.equalsIgnoreCase("Enter Username...") || password.equalsIgnoreCase("Enter Password...")
                || reTypePassword.equalsIgnoreCase("Retype Password...")
                || name.equalsIgnoreCase("Enter Name..") || username.equalsIgnoreCase("") || password.equalsIgnoreCase("")
                || reTypePassword.equalsIgnoreCase("")
                || name.equalsIgnoreCase("") || name.equalsIgnoreCase("") || contact.equals("Enter Contact...") || contact.equals("") || address.equals("Enter Address..") || address.equals(""))) {

            if (reTypePassword.equals(password)) {
                if (contact.matches("^[0][1-9]\\d{9}$|^[1-9]\\d{9}$")) {
                    int status = dbManager.insertUser(
                            new User(0, user_type_id, this.jTextFieldUsername.getText(), this.jTextFieldPassword.getText(),
                                    this.jTextFieldName.getText(),
                                    address, contact, 1));

                    if (status != 0) {
                        JOptionPane.showMessageDialog(this, "Successfully added");
                        this.jTextFieldUsername.setText("Enter Username...");
                        this.jTextFieldPassword.setText("Enter Password...");
                        this.jTextFieldRetypePassword.setText("Retype Password...");
                        this.jTextFieldContact.setText("Enter Contact..");
                        this.jTextFieldAddress.setText("Enter Address...");
                        this.jTextFieldName.setText("Enter Name..");
                        this.jComboBoxUserType.setSelectedIndex(0);

                        this.jLabelRetype.setForeground(Color.gray);
                        this.jTextFieldUsername.setForeground(Color.gray);
                        this.jTextFieldPassword.setForeground(Color.gray);
                        this.jTextFieldRetypePassword.setForeground(Color.gray);
                        this.jTextFieldContact.setForeground(Color.gray);
                        this.jTextFieldAddress.setForeground(Color.gray);
                        this.jTextFieldName.setForeground(Color.gray);

                    }
                } else {
                    new playAudio().playErrorSound();

                    JOptionPane.showMessageDialog(this, "Invalid phone number", "Error", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                new playAudio().playErrorSound();
                this.jLabelRetype.setForeground(Color.red);
                JOptionPane.showMessageDialog(this, "Password not match", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            new playAudio().playErrorSound();

            JOptionPane.showMessageDialog(this, "Please fill required field", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButtonSave1ActionPerformed

    private void jButtonSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSave2ActionPerformed

        int user_type_id = user_types_list.get(this.jComboBoxUserType.getSelectedIndex()).getUser_type_id();

        String username = this.jTextFieldUsername.getText();
        String password = this.jTextFieldPassword.getText();
        String reTypePassword = this.jTextFieldRetypePassword.getText();
        String name = this.jTextFieldName.getText();
        String contact = this.jTextFieldContact.getText();
        String address = this.jTextFieldAddress.getText();

        if (!(username.equalsIgnoreCase("Enter Username...") || password.equalsIgnoreCase("Enter Password...")
                || reTypePassword.equalsIgnoreCase("Retype Password...")
                || name.equalsIgnoreCase("Enter Name..") || username.equalsIgnoreCase("") || password.equalsIgnoreCase("")
                || reTypePassword.equalsIgnoreCase("")
                || name.equalsIgnoreCase("") || name.equalsIgnoreCase("") || contact.equals("Enter Contact...") || contact.equals("") || address.equals("Enter Address..") || address.equals(""))) {

            if (reTypePassword.equals(password)) {
                if (contact.matches("^[0][1-9]\\d{9}$|^[1-9]\\d{9}$")) {
                    int status = dbManager.insertUser(
                            new User(0, user_type_id, this.jTextFieldUsername.getText(), this.jTextFieldPassword.getText(),
                                    this.jTextFieldName.getText(),
                                    address, contact, 1));

                    if (status != 0) {
                        JOptionPane.showMessageDialog(this, "Successfully added");
                        this.jTextFieldUsername.setText("Enter Username...");
                        this.jTextFieldPassword.setText("Enter Password...");
                        this.jTextFieldRetypePassword.setText("Retype Password...");
                        this.jTextFieldContact.setText("Enter Contact..");
                        this.jTextFieldAddress.setText("Enter Address...");
                        this.jTextFieldName.setText("Enter Name..");
                        this.jComboBoxUserType.setSelectedIndex(0);

                        this.jLabelRetype.setForeground(Color.gray);
                        this.jTextFieldUsername.setForeground(Color.gray);
                        this.jTextFieldPassword.setForeground(Color.gray);
                        this.jTextFieldRetypePassword.setForeground(Color.gray);
                        this.jTextFieldContact.setForeground(Color.gray);
                        this.jTextFieldAddress.setForeground(Color.gray);
                        this.jTextFieldName.setForeground(Color.gray);

                    }
                } else {
                    new playAudio().playErrorSound();

                    JOptionPane.showMessageDialog(this, "Invalid phone number", "Error", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                new playAudio().playErrorSound();
                this.jLabelRetype.setForeground(Color.red);
                JOptionPane.showMessageDialog(this, "Password not match", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            new playAudio().playErrorSound();

            JOptionPane.showMessageDialog(this, "Please fill required field", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButtonSave2ActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogBox dialog = new DialogBox(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void showInUserTypesComboBox() {
        user_types_list = dbManager.getAllUsersType();
        for (UserType userType : user_types_list) {

            this.jComboBoxUserType.addItem("" + userType.getUser_type());

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSave1;
    private javax.swing.JButton jButtonSave2;
    private javax.swing.JComboBox<String> jComboBoxUserType;
    private javax.swing.JComboBox<String> jComboBoxUserType2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelHeaderRow;
    private javax.swing.JLabel jLabelRetype;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldContact;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JPasswordField jTextFieldPassword;
    private javax.swing.JPasswordField jTextFieldRetypePassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
